# Generated by Django 4.1.1 on 2022-10-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_qtd_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='qtd_total',
            field=models.PositiveIntegerField(),
        ),
    ]
